[package]
name = "chess_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.21.1", features = ["extension-module"] }

[build-dependencies]
maturin = "1.5.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "chess_ai"
